version: '3.9'

services:
  bot:
    build:
      context: .
      dockerfile: resources/docker/Dockerfile
    volumes:
      - ./src:/app
    env_file: $PWD/src/.env
    command: go run .
    ports:
      - 9888:9888
    networks:
      - internal

  go:
    build:
      context: .
      dockerfile: resources/docker/Dockerfile
    entrypoint: [ "go" ]
    working_dir: /app
    command: [ "-v" ]
    volumes:
      - ./src:/app

networks:
  internal:
    driver: bridge